name: "Deploy - código facilito"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigo-facilito:
    runs-on: ubuntu-latest
    steps:
      run: echo "Se hizo pull del código"
      run: echo "Correr migraciones"
      run: echo "Generar binario"
      run: echo "Publicar versión"